# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFilesOverSSH@0
  inputs:
    sshEndpoint: 'TestVM-SSH'
    contents: 'index.html'
    targetFolder: '/usr/share/nginx'
    readyTimeout: '20000'
    failOnEmptySource: true
- task: SSH@0
  inputs:
    sshEndpoint: 'TestVM-SSH'
    runOptions: 'commands'
    commands: 'curl 127.0.0.1'
    readyTimeout: '20000'